apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: proxy-failure
  namespace: jctest
spec:
  action: pod-failure
  mode: fixed-percent
  value: "100"
  duration: "1h"
  selector:
    labelSelectors:
      "validator-proxied": "jctest-validators-0"
  scheduler:
    cron: "@every 24h"

