apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app: voting-bot
    chart: voting-bot
    release: {{ .Release.Service }}
    component: voting-bot
spec:
  schedule: "{{ .Values.cronSchedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: voting-bot
            image: