{{ range $index, $e := until (int .Values.replicaCount ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" $ }}-{{ $index }}
  annotations:
{{ if $.Values.azure }}
    service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"
{{ end }}
  labels:
{{ include "celo-fullnode.labels" $ | indent 4 }}
spec:
  type: {{ $.Values.geth.service_type }}
  publishNotReadyAddresses: true
{{- if (and $.Values.geth.use_static_ips $.Values.azure) }}
  loadBalancerIP: {{ index $.Values.geth.public_ips $index -}}
{{- end }}
  ports:
{{- range $protocol, $node_port := (index $.Values.geth.service_node_port_per_full_node $index) }}
    - targetPort: ethereum
      port: 30303
      nodePort: {{ $node_port }}
      name: {{ lower $protocol }}
      protocol: {{ $protocol }}
{{- end }}
    # - port: 30303
    #   targetPort: ethereum
    #   name: ethereum
{{- if $.Values.geth.expose_rpc_externally }}
{{ include "celo-fullnode.rpc-ports" . | indent 4 }}
{{- end }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ template "common.fullname" $ }}-{{ $index }}
---
{{ end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-rpc
  labels:
{{ include "celo-fullnode.labels" .  | indent 4 }}
spec:
  type: ClusterIP
  ports:
{{ include "celo-fullnode.rpc-ports" . | indent 4 }}
  selector:
{{ include "celo-fullnode.labels" .  | indent 4 }}
