{{ range $index, $e := until (int .Values.replicaCount ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" $ }}-{{ $index }}
  annotations:
  # if values.geth.azureprovider, use below, else use aws
  # service.beta.kubernetes.io/azure-load-balancer-mixed-protocols: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: {{ index $.Values.geth.eip_allocation_ids $index }}
  labels:
{{ include "celo-fullnode.labels" $ | indent 4 }}
spec:
  type: {{ $.Values.geth.service_type }}
{{- if (and $.Values.geth.use_static_ips $.Values.geth.azure_provider) }}
  loadBalancerIP: {{ index $.Values.geth.public_ips $index -}}
{{- end }}
  ports:
    - port: 30303
      targetPort: ethereum
      name: ethereum
{{- if $.Values.geth.expose_rpc_externally }}
{{ include "celo-fullnode.rpc-ports" . | indent 4 }}
{{- end }}
  selector:
    statefulset.kubernetes.io/pod-name: {{ template "common.fullname" $ }}-{{ $index }}
---
{{ end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-rpc
  labels:
{{ include "celo-fullnode.labels" .  | indent 4 }}
spec:
  type: ClusterIP
  ports:
{{ include "celo-fullnode.rpc-ports" . | indent 4 }}
  selector:
{{ include "celo-fullnode.labels" .  | indent 4 }}
