apiVersion: v1
kind: Service
metadata:
  name: oracle
  labels:
    component: oracle
spec:
  clusterIP: None
  selector:
    component: oracle
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.environmentName }}-oracle
  # annotations:
    # prometheus.io/scrape: true
  labels:
    # TODO add labels
    component: oracle
spec:
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  replicas: {{ .Values.replicas }}
  serviceName: oracle
  selector:
    matchLabels:
      # TODO add labels
      component: oracle
  template:
    metadata:
      labels:
# TODO add labels
        component: oracle
    spec:
      containers:
      - name: geth
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        env:
        - name: WEB3_PROVIDER_URL
          value: {{ .Values.oracle.web3ProviderUrl }}
        # ports:
        # - name: prometheus-server
        #   containerPort: 9090
        # resources:
        #   requests:
        #     memory: {{ .Values.pod.memoryRequest }}
        #     cpu: {{ .Values.pod.cpuRequest }}
