apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  labels:
{{ include "prometheus-stackdriver.labels" .  | indent 4 }}
spec:
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}
