# This file is intended to show the expected value structure with placeholder values.
# Many values are optional, and the defaults are left up to the client.
# These values are commented out in this file, but show the correct structure
# if they were to be specified.

environment:
  name: test

kubectl:
  image:
    repository: bitnami/kubectl
    tag: 1.17.4

relayer:
  image:
    repository: celotestnet.azurecr.io/komenci/relayer
    tag: latest
  replicas: 2
  rpcProviderUrls:
    ws: wss://alfajoresstaging-forno.celo-testnet.org
    http: https://alfajoresstaging-forno.celo-testnet.org
  identities:
  - address: 0x00454cac6dae53f8800f71395b9a174f07a784b1
    privateKey: 0x000
    azure:
      id: defaultId
      clientId: defaultClientId
      keyVaultName: staging-komenci-eus
  - address: 0xc6f0f9bfb1aed83620ece3eac0add98a65a8574e
    privateKey: 0x001
    azure:
      id: defaultId1
      clientId: defaultClientId1
      keyVaultName: staging-komenci-eus
  azureHsm:
    initTryCount: 5
    initMaxRetryBackoffMs: 30000
  aggregation:
    mid:
      maxExchangeVolumeShare: 1
      askMaxPercentageDeviation: 0.05
      bidMaxPercentageDeviation: 0.05
      maxPercentageBidAskSpread: 0.025
      # minReportPriceChangeThreshold
    trades:
      periodMs: 300000
      # dataFetchFrequency
      # minimumTrades
      # scalingRate
  baseCurrency: GoldToken
  quoteCurrency: USD
  token: StableToken
  metrics:
    enabled: true
    prometheusPort: 9090
  allowNotCGLD: false
  apiRequestTimeoutMs: 5000
  circuitBreakerPriceChangeThreshold: 0.25
  exchanges: BITTREX,OKCOIN,COINBASE
  reportStrategy: BLOCK_BASED
  reporter:
    blockBased:
      minReportPriceChangeThreshold: 0.005 # 0.5%
      # targetMaxHeartbeatPeriodMs
    timer:
      removeExpiredFrequencyMs: 60000
      # removeExpiredOffsetOverride
      # removeFrequencyOverride
      # reportOffsetOverride
  # privateKeyPath
  # unusedOracleAddresses
  # overrideIndex
  # overrideOracleCount
  # maxBlockTimestampAgeMs

onboarding:
  image: 
    repository: celotestnet.azurecr.io/komenci/onboarding
    tag: latest
  replicas: 2
