apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
{{ include "labels" . | indent 4 }}
{{ include "komenci-onboarding-component-label" . | indent 4 }}
spec:
  clusterIP: None
  selector:
{{ include "komenci-onboarding-component-label" . | indent 4 }}
---