apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: komenci-onboarding-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - {{ .Release.Namespace }}.{{ .Values.domain.name }}.org
    secretName: {{ .Release.Namespace }}-web-tls
  rules:
  - host: {{ .Release.Namespace }}.{{ .Values.domain.name }}.org
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Namespace }}-onboarding
          servicePort: 3000