apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "komenci-onboarding.fullname" . }}
  labels:
    {{- include "komenci-onboarding.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.onboarding.replicaCount }}
  selector:
    matchLabels:
      {{- include "komenci-onboarding.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "komenci-onboarding.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.onboarding.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "komenci-onboarding.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.onboarding.image.repository }}::{{ .Values.onboarding.image.tag }}
          imagePullPolicy: {{ .Values.onboarding.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.onboarding.resources | nindent 12 }}
      {{- with .Values.onboarding.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.onboarding.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.onboarding.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
