apiVersion: v1
kind: Service
metadata:
  name: {{ include "komenci-onboarding-fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
{{ include "komenci-onboarding-component-label" . | indent 4 }}
spec:
  clusterIP: None
  selector:
{{ include "komenci-onboarding-component-label" . | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "komenci-onboarding-fullname" . }}
  labels:
{{- include "komenci-onboarding-component-label" . | nindent 4 }}
spec:
  replicas: {{ .Values.onboarding.replicaCount }}
  selector:
    matchLabels: 
    {{- include "komenci-onboarding-component-label" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "komenci-onboarding-component-label" . | nindent 8 }}
    spec:
    {{- with .Values.onboarding.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "komenci-onboarding-fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.onboarding.image.repository }}::{{ .Values.onboarding.image.tag }}
          imagePullPolicy: {{ .Values.onboarding.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.onboarding.resources | nindent 12 }}
      {{- with .Values.onboarding.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.onboarding.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.onboarding.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
