apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  labels:
    app: voting-bot
    chart: voting-bot
    release: {{ .Release.Service }}
    component: voting-bot
spec:
  schedule: "{{ .Values.cronSchedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: voting-bot
            image: {{ .Values.imageRepository }}.{{ .Values.imageTag }}
            imagePullPolicy: {{ .Values.imagePullPolicy }}
            command:
              - bash
              - "-c"
              - |
                CELOTOOL="/celo-monorepo/packages/celotool/bin/celtooljs.sh";

                $CELOTOOL bots auto-vote --celoProvider https://{{ .Release.Namespace }}-forno.{{ .Values.domain.name }}.org
            env:
            - name: MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.environment }}-voting-bot-secrets
                  key: mnemonic
            - name: VOTING_BOT_CHANGE_PROBABILITY
              value: {{ .Values.voteChangeProbability | quote }}
            - name: VOTING_BOTS
              value: {{ .Values.votingBotCount | quote }}
          restartPolicy: Never
