name: build

on: [push, pull_request]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
    instrumentation-tests:
        name: Instrumentation tests
        runs-on: macos-latest
        timeout-minutes: 60
        strategy:
            fail-fast: true
            matrix:
                api-level: [29]
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
            - uses: actions/setup-java@v1
              with:
                java-version: '8'
            - uses: actions/setup-node@v1
            - run: yarn
            - run: yarn build --scope @celo/mobile --include-filtered-dependencies
            - uses: reactivecircus/android-emulator-runner@v2
              with:
                api-level: ${{ matrix.api-level }}
                arch: x86
                avd-name: Nexus_5X_API_28_x86
                emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
                working-directory: ./packages/mobile
                script: yarn run test:e2e:android
